### ISSUE TITLE
[Notice] PR 요청 시 템플릿

### ISSUE THREAD

**Issue by phainestha1** [DeveloperAcademy-POSTECH/MC3_TEAM1_LATER#18]
PR 요청 시 아래 내용을 복사하시어 관련 내용을 작성해주세요
새로운 View가 생겼다면 해당 파일의 스크린샷도 첨부해주세요.

------------------------------------------------------------------

`##개요`

`## PR 타입 (하나 이상의 PR 타입을 선택해주세요)`

`- [x]  기능 추가`
`- [ ]  기능 삭제`
`- [ ]  버그 수정`
`- [ ]  의존성, 환경 변수, 빌드 관련 코드 업데이트`

`## 주요 작업 사항`

`## 적용 파일`

------------------------------------------------------------------

적용 예시

## PR 타입 (하나 이상의 PR 타입을 선택해주세요)

- [x]  기능 추가
- [ ]  기능 삭제
- [ ]  버그 수정
- [ ]  의존성, 환경 변수, 빌드 관련 코드 업데이트

## 적용 파일

------------------------------------------------------------------

**Comment by DevLuce** [comment]
확인했습니닷!
