### ISSUE TITLE
View Integration 

### ISSUE THREAD

**Issue by myungjinsim** [DeveloperAcademy-POSTECH/MC3_TEAM1_LATER#37]

**Comment by phainestha1** [comment]
@myungjinsim 
탭뷰를 통해 모든 뷰를 연결한 후 기획했던 플로우가 작동하면 해당 이슈 클로즈하겠습니다.

**Comment by phainestha1** [comment]
상기 내용 적용되어 클로즈 하였습니다.
[https://github.com/DeveloperAcademy-POSTECH/MC3_TEAM1_LATER/pull/58](url)
